#
# This workflow will build codebase, run linting and test cases on every PR
# and push into develop and master branches.
#
name: Build - PR

on:
  push:
    branches: [ master ]

  pull_request:
    types: [ opened, synchronize, reopned ]
    branches: [ master ]

jobs:

  build:
    name: Build, Lint and Unit Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 10.15.3

      - name: Install Dependencies
        run: npm ci

      - name: Execute Unit Tests
        run: npm run test

#
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@c35654669e40ece974c8835211c2e8ad9c802df0 # pin@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
